config/routes.rb
Calculator::Application.routes.draw do
  root 'car#index'

  resources :car

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  def index

  end
end

app/controllers/car_controller.rb
class CarController < ApplicationController

  def index
    @cars = Car.all
  end

  def show

  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/views/car/create.html.erb
<h1>Cars</h1>

<ul>
  <li><%= link_to "All", car_index_path %></li>
  <li><%= link_to "New", new_car_path %></li>
</ul>

app/views/car/destroy.html.erb
<h1>Cars</h1>

<ul>
  <li><%= link_to "All", car_index_path %></li>
  <li><%= link_to "New", new_car_path %></li>
</ul>

app/views/car/edit.html.erb
<h1>Cars</h1>

<ul>
  <li><%= link_to "All", car_index_path %></li>
  <li><%= link_to "New", new_car_path %></li>
</ul>

app/views/car/index.html.erb
<h1>Cars</h1>

<ul>
  <li><%= link_to "All", car_index_path %></li>
  <li><%= link_to "New", new_car_path %></li>
</ul>

<ul>
  <% @cars.each do |car| %>
    <li>
      <%= link_to "#{ car.make } - #{ car.model }", car_path(car) %>
      <span><%= link_to "Edit", edit_car_path(car) %><span>
        <span><%= link_to "Delete", car_path(car), method: :delete %><span>
    </li>
  <% end %>
</ul>

app/views/car/new.html.erb
<h1>Cars</h1>

<ul>
  <li><%= link_to "All", car_index_path %></li>
  <li><%= link_to "New", new_car_path %></li>
</ul>

app/views/car/show.html.erb
<h1>Cars</h1>

<ul>
  <li><%= link_to "All", car_index_path %></li>
  <li><%= link_to "New", new_car_path %></li>
</ul>

app/views/car/update.html.erb
<h1>Cars</h1>

<ul>
  <li><%= link_to "All", car_index_path %></li>
  <li><%= link_to "New", new_car_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculator</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>